package com.anteaters.boggle;

import com.anteaters.boggle.service.BoggleBoard;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.util.LinkedList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for {@link BoggleBoard}.
 *
 * <p><b>AI-GENERATED:</b> This test class was generated by AI, namely Opus4.7.
 *
 * <h2>What this test class covers</h2>
 * {@code BoggleBoard} is a pure-Java domain class (no Spring dependencies), so
 * these tests use plain JUnit 5 without any application-context bootstrapping.
 *
 * <p>Coverage goals:
 * <ul>
 *   <li>The two public constructors (default size 5, size-arg with clamping).</li>
 *   <li>Size clamping: any value below 3 becomes 3, any value above 10 becomes 10.</li>
 *   <li>{@link BoggleBoard#boardToStringArray()} returns a fully populated 2-D
 *       string grid whose dimensions match the (possibly clamped) size.</li>
 *   <li>Every cell contains a non-null, non-empty letter drawn from the
 *       canonical Boggle dice pool.</li>
 *   <li>{@link BoggleBoard#addLetter} accepts an initial die, rejects a
 *       non-adjacent second die, and rejects re-using an already-used die.</li>
 *   <li>{@link BoggleBoard#removeLetter()} is a no-op on an empty entry list
 *       and removes the most recently added die otherwise.</li>
 * </ul>
 *
 * <p>Private/package-private state (such as the {@code currentEntry} list) is
 * inspected via reflection so we can assert on behavior without modifying the
 * production class.
 */
public class BoggleBoardTest {

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Verifies that the no-arg constructor produces a 5x5 board whose string
     * representation has the expected dimensions.
     */
    @Test
    void defaultConstructor_producesFivebyFiveBoard() {
        BoggleBoard board = new BoggleBoard();
        String[][] grid = board.boardToStringArray();

        assertEquals(5, grid.length, "default board should have 5 rows");
        for (String[] row : grid) {
            assertEquals(5, row.length, "default board rows should be length 5");
        }
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Verifies that the sized constructor honors the caller's size when it is
     * within the legal 3-10 inclusive range.
     */
    @Test
    void sizedConstructor_usesRequestedSizeInBounds() {
        for (int size = 3; size <= 10; size++) {
            BoggleBoard board = new BoggleBoard(size);
            String[][] grid = board.boardToStringArray();
            assertEquals(size, grid.length, "row count should match requested size " + size);
            assertEquals(size, grid[0].length, "col count should match requested size " + size);
        }
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Verifies that requesting a size below the minimum (3) is clamped up,
     * and requesting a size above the maximum (10) is clamped down.
     */
    @Test
    void sizedConstructor_clampsOutOfRangeSizes() {
        BoggleBoard tooSmall = new BoggleBoard(1);
        BoggleBoard tooLarge = new BoggleBoard(42);

        assertEquals(3, tooSmall.boardToStringArray().length,
                "size below minimum should clamp to 3");
        assertEquals(10, tooLarge.boardToStringArray().length,
                "size above maximum should clamp to 10");
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Verifies every cell of a freshly constructed board carries a non-null,
     * non-empty face string. This catches populate-order bugs where a die could
     * be left unassigned.
     */
    @Test
    void boardToStringArray_everyCellIsPopulated() {
        BoggleBoard board = new BoggleBoard(6);
        String[][] grid = board.boardToStringArray();

        for (int r = 0; r < grid.length; r++) {
            for (int c = 0; c < grid[r].length; c++) {
                String face = grid[r][c];
                assertNotNull(face, "cell [" + r + "][" + c + "] should not be null");
                assertFalse(face.isBlank(),
                        "cell [" + r + "][" + c + "] should not be blank");
            }
        }
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Verifies {@link BoggleBoard#printBoard()} does not throw when run on a
     * freshly constructed board. This guards against null-face regressions that
     * would surface as a {@link NullPointerException} during printing.
     */
    @Test
    void printBoard_doesNotThrow() {
        BoggleBoard board = new BoggleBoard();
        assertDoesNotThrow(board::printBoard);
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Exercises the entry-validation path in {@link BoggleBoard#addLetter}:
     * <ol>
     *   <li>The first die added (0,0) is always accepted.</li>
     *   <li>A non-adjacent die (0,3) is rejected.</li>
     *   <li>A die reusing the same coordinates as an already-used die is rejected.</li>
     *   <li>An adjacent, unused die (1,1) is accepted.</li>
     * </ol>
     * State is checked by reading the package-private {@code currentEntry} via
     * reflection, since no public getter is exposed.
     */
    @Test
    void addLetter_enforcesAdjacencyAndNoReuse() throws Exception {
        BoggleBoard board = new BoggleBoard();

        BoggleBoard.Dice first = board.new Dice(List.of("A", "B", "C", "D", "E", "F"));
        first.setCoordinates(0, 0);

        BoggleBoard.Dice farAway = board.new Dice(List.of("A", "B", "C", "D", "E", "F"));
        farAway.setCoordinates(0, 3); // not adjacent to (0,0)

        BoggleBoard.Dice reusedSpot = board.new Dice(List.of("A", "B", "C", "D", "E", "F"));
        reusedSpot.setCoordinates(0, 0); // already used

        BoggleBoard.Dice neighbor = board.new Dice(List.of("A", "B", "C", "D", "E", "F"));
        neighbor.setCoordinates(1, 1); // diagonally adjacent to (0,0)

        board.addLetter(first);
        board.addLetter(farAway);
        board.addLetter(reusedSpot);
        board.addLetter(neighbor);

        LinkedList<?> entry = readCurrentEntry(board);
        assertAll(
                () -> assertEquals(2, entry.size(),
                        "only the first and the adjacent die should be accepted"),
                () -> assertTrue(entry.contains(first), "first die should be present"),
                () -> assertTrue(entry.contains(neighbor), "adjacent die should be present")
        );
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Verifies {@link BoggleBoard#removeLetter()} safely handles an empty
     * entry list (no exception) and removes the most recently added die when
     * the entry list is non-empty.
     */
    @Test
    void removeLetter_isSafeOnEmptyAndPopsMostRecent() throws Exception {
        BoggleBoard board = new BoggleBoard();

        // Empty removal should not throw.
        assertDoesNotThrow(board::removeLetter);

        BoggleBoard.Dice a = board.new Dice(List.of("A", "B", "C", "D", "E", "F"));
        a.setCoordinates(0, 0);
        BoggleBoard.Dice b = board.new Dice(List.of("A", "B", "C", "D", "E", "F"));
        b.setCoordinates(1, 1);

        board.addLetter(a);
        board.addLetter(b);
        board.removeLetter();

        LinkedList<?> entry = readCurrentEntry(board);
        assertEquals(1, entry.size(), "removeLetter should shrink the entry");
        assertTrue(entry.contains(a), "the earlier die should remain");
        assertFalse(entry.contains(b), "the most recent die should be gone");
    }

    /**
     * <p><b>AI-GENERATED:</b> This helper was generated by AI, namely Opus4.7.
     *
     * <p>Reflection helper that reads the package-private {@code currentEntry}
     * field so tests in a different package can assert on internal state
     * without modifying production code.
     */
    private static LinkedList<?> readCurrentEntry(BoggleBoard board) throws Exception {
        Field f = BoggleBoard.class.getDeclaredField("currentEntry");
        f.setAccessible(true);
        return (LinkedList<?>) f.get(board);
    }
}
