package com.anteaters.boggle;

import com.anteaters.boggle.dictionary.InMemoryCustomDictionaryStore;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for {@link InMemoryCustomDictionaryStore}.
 *
 * <p><b>AI-GENERATED:</b> This test class was generated by AI, namely Opus4.7.
 *
 * <h2>What this test class covers</h2>
 * {@code InMemoryCustomDictionaryStore} is a plain {@code @Component} that
 * wraps a {@link java.util.concurrent.ConcurrentHashMap}. No Spring context is
 * needed — the class can be instantiated directly with {@code new}.
 *
 * <p>Coverage goals:
 * <ul>
 *   <li>{@code addWord} returns {@code true} on first insert and {@code false}
 *       on duplicate insert within the same scope.</li>
 *   <li>{@code removeWord} returns {@code true} only when the word was
 *       actually present and {@code false} otherwise.</li>
 *   <li>{@code contains} returns the correct presence state after a sequence
 *       of adds and removes.</li>
 *   <li>{@code listWords} returns every added word and is unmodifiable (i.e.
 *       mutation attempts throw {@link UnsupportedOperationException}).</li>
 *   <li>Scopes are isolated from one another: adding to scope A must not leak
 *       into scope B. This prepares the store for future per-room scoping.</li>
 * </ul>
 */
public class InMemoryCustomDictionaryStoreTest {

    private static final String SCOPE = "GLOBAL";
    private static final String OTHER_SCOPE = "ROOM-42";

    private InMemoryCustomDictionaryStore store;

    /**
     * <p><b>AI-GENERATED:</b> This setup method was generated by AI, namely Opus4.7.
     *
     * <p>Creates a fresh store before each test so state does not leak between
     * cases.
     */
    @BeforeEach
    void setUp() {
        store = new InMemoryCustomDictionaryStore();
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>The first {@code addWord} call for a given (scope, word) pair should
     * return {@code true}. A second call with the same pair should return
     * {@code false} because the underlying {@link Set} rejects duplicates.
     */
    @Test
    void addWord_firstInsertSucceedsSecondIsDuplicate() {
        assertTrue(store.addWord(SCOPE, "APPLE"), "first add should succeed");
        assertFalse(store.addWord(SCOPE, "APPLE"), "duplicate add should return false");
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>{@code removeWord} should return {@code true} only when it actually
     * removed an entry. Removing an unknown word should return {@code false}.
     */
    @Test
    void removeWord_reportsWhetherEntryExisted() {
        store.addWord(SCOPE, "APPLE");

        assertTrue(store.removeWord(SCOPE, "APPLE"), "removing an existing word should return true");
        assertFalse(store.removeWord(SCOPE, "APPLE"), "removing it again should return false");
        assertFalse(store.removeWord(SCOPE, "NEVER_ADDED"),
                "removing a word that was never added should return false");
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>{@code contains} should track the full lifecycle of a word: absent
     * before add, present after add, absent again after remove.
     */
    @Test
    void contains_tracksAddThenRemove() {
        assertFalse(store.contains(SCOPE, "APPLE"), "word should be absent before add");

        store.addWord(SCOPE, "APPLE");
        assertTrue(store.contains(SCOPE, "APPLE"), "word should be present after add");

        store.removeWord(SCOPE, "APPLE");
        assertFalse(store.contains(SCOPE, "APPLE"), "word should be absent after remove");
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>{@code listWords} should contain every word added to the scope and
     * should be unmodifiable — any attempt to mutate the returned set must
     * throw {@link UnsupportedOperationException}. This is important because
     * the store's contract returns the view to untrusted callers.
     */
    @Test
    void listWords_returnsAllWordsAndIsUnmodifiable() {
        store.addWord(SCOPE, "APPLE");
        store.addWord(SCOPE, "BANANA");
        store.addWord(SCOPE, "CHERRY");

        Set<String> words = store.listWords(SCOPE);

        assertEquals(3, words.size(), "should contain every added word");
        assertTrue(words.contains("APPLE"));
        assertTrue(words.contains("BANANA"));
        assertTrue(words.contains("CHERRY"));

        assertThrows(UnsupportedOperationException.class,
                () -> words.add("DATE"),
                "the returned set must be unmodifiable");
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Words added in one scope must not appear in another. This guards the
     * scoping contract that will later be used for per-room dictionaries.
     */
    @Test
    void scopes_areIsolatedFromEachOther() {
        store.addWord(SCOPE, "APPLE");
        store.addWord(OTHER_SCOPE, "ORANGE");

        assertTrue(store.contains(SCOPE, "APPLE"));
        assertFalse(store.contains(SCOPE, "ORANGE"), "ORANGE was added to a different scope");

        assertTrue(store.contains(OTHER_SCOPE, "ORANGE"));
        assertFalse(store.contains(OTHER_SCOPE, "APPLE"), "APPLE was added to a different scope");

        assertEquals(Set.of("APPLE"), store.listWords(SCOPE));
        assertEquals(Set.of("ORANGE"), store.listWords(OTHER_SCOPE));
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>{@code listWords} on an unknown scope should return an empty set
     * rather than {@code null}, matching the store's lazy-create contract.
     */
    @Test
    void listWords_unknownScopeReturnsEmptySet() {
        Set<String> words = store.listWords("NEVER_USED_SCOPE");
        assertTrue(words.isEmpty(), "unknown scope should lazily produce an empty set");
    }
}
