package com.anteaters.boggle;

import com.anteaters.boggle.dictionary.CustomDictionaryStorable;
import com.anteaters.boggle.dictionary.DictionaryTrie;
import com.anteaters.boggle.service.WordVerificationService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Unit tests for {@link WordVerificationService}.
 *
 * <p><b>AI-GENERATED:</b> This test class was generated by AI, namely Opus4.7.
 *
 * <h2>What this test class covers</h2>
 * {@code WordVerificationService} is a plain {@code @Service} with two
 * collaborators ({@link DictionaryTrie} and {@link CustomDictionaryStorable}).
 * No Spring context is needed — we construct the service directly and pass
 * Mockito mocks to isolate business logic from real dictionary state.
 *
 * <p>Coverage goals:
 * <ul>
 *   <li>Null input returns {@code false} without touching either dictionary.</li>
 *   <li>Inputs shorter than 3 characters (after trimming) are rejected early
 *       without consulting either dictionary.</li>
 *   <li>Inputs containing any non A-Z character (after normalizing) are
 *       rejected early without consulting either dictionary.</li>
 *   <li>A word found in the base {@link DictionaryTrie} returns {@code true}
 *       and short-circuits the custom-dictionary lookup.</li>
 *   <li>A word absent from the base trie but present in the custom store
 *       returns {@code true}.</li>
 *   <li>A word absent from both stores returns {@code false}.</li>
 *   <li>Input is normalized via {@code trim() + toUpperCase()} before being
 *       passed to the dictionaries.</li>
 *   <li>The scoped overload {@code isValidWord(rawInput, scopeKey)} forwards
 *       the given scope to the custom store instead of {@code GLOBAL_SCOPE}.</li>
 *   <li>The no-scope overload defaults to {@link WordVerificationService#GLOBAL_SCOPE}.</li>
 * </ul>
 */
public class WordVerificationServiceTest {

    private DictionaryTrie trie;
    private CustomDictionaryStorable customStore;
    private WordVerificationService service;

    /**
     * <p><b>AI-GENERATED:</b> This setup method was generated by AI, namely Opus4.7.
     *
     * <p>Creates fresh Mockito mocks and a fresh service before each test so
     * interactions do not leak between cases.
     */
    @BeforeEach
    void setUp() {
        trie = mock(DictionaryTrie.class);
        customStore = mock(CustomDictionaryStorable.class);
        service = new WordVerificationService(trie, customStore);
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>A {@code null} input should short-circuit to {@code false} without
     * consulting either dictionary. This guards against accidental NPEs in the
     * normalization path.
     */
    @Test
    void isValidWord_nullInput_returnsFalseAndSkipsDictionaries() {
        assertFalse(service.isValidWord(null));

        verify(trie, never()).contains(anyString());
        verify(customStore, never()).contains(anyString(), anyString());
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Inputs that are shorter than 3 characters after trimming should fail
     * the length guard and never consult the dictionaries.
     */
    @Test
    void isValidWord_tooShortInput_returnsFalseAndSkipsDictionaries() {
        assertFalse(service.isValidWord(""));
        assertFalse(service.isValidWord("ab"));
        assertFalse(service.isValidWord("  a  ")); // trims to "A"

        verify(trie, never()).contains(anyString());
        verify(customStore, never()).contains(anyString(), anyString());
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Inputs containing any character outside A-Z (after uppercasing) must
     * be rejected without consulting the dictionaries. Covers digits,
     * punctuation, and internal whitespace.
     */
    @Test
    void isValidWord_nonAlphabeticInput_returnsFalseAndSkipsDictionaries() {
        assertFalse(service.isValidWord("abc1"));
        assertFalse(service.isValidWord("hello!"));
        assertFalse(service.isValidWord("two words"));

        verify(trie, never()).contains(anyString());
        verify(customStore, never()).contains(anyString(), anyString());
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>When the base trie reports a hit, the service returns {@code true}
     * and should not bother querying the custom store (short-circuit OR).
     */
    @Test
    void isValidWord_hitInBaseTrie_shortCircuitsCustomStore() {
        when(trie.contains("APPLE")).thenReturn(true);

        assertTrue(service.isValidWord("APPLE"));

        verify(trie).contains("APPLE");
        verify(customStore, never()).contains(anyString(), anyString());
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>When the base trie misses but the custom store hits, the overall
     * result should still be {@code true}.
     */
    @Test
    void isValidWord_missingFromTrieButInCustomStore_returnsTrue() {
        when(trie.contains("ZZZCUSTOM")).thenReturn(false);
        when(customStore.contains(WordVerificationService.GLOBAL_SCOPE, "ZZZCUSTOM"))
                .thenReturn(true);

        assertTrue(service.isValidWord("ZZZCUSTOM"));

        verify(trie).contains("ZZZCUSTOM");
        verify(customStore).contains(WordVerificationService.GLOBAL_SCOPE, "ZZZCUSTOM");
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>A word that is absent from both the base trie and the custom store
     * should return {@code false}.
     */
    @Test
    void isValidWord_missingFromBothDictionaries_returnsFalse() {
        when(trie.contains(anyString())).thenReturn(false);
        when(customStore.contains(anyString(), anyString())).thenReturn(false);

        assertFalse(service.isValidWord("XYZZYX"));

        verify(trie).contains("XYZZYX");
        verify(customStore).contains(WordVerificationService.GLOBAL_SCOPE, "XYZZYX");
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Input must be normalized before dictionary lookup: surrounding
     * whitespace is trimmed and casing is uppercased. The dictionaries should
     * be queried with the normalized form, not the raw input.
     */
    @Test
    void isValidWord_normalizesInputBeforeLookup() {
        when(trie.contains("APPLE")).thenReturn(true);

        assertTrue(service.isValidWord("  apple  "));

        verify(trie).contains("APPLE");
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>The scoped overload must pass the caller-provided scope key through
     * to the custom store instead of {@code GLOBAL_SCOPE}. This guards the
     * room-scoped dictionary feature from regressions.
     */
    @Test
    void isValidWord_scopedOverload_forwardsScopeToCustomStore() {
        String scope = "ROOM-42";
        when(trie.contains("ZZZCUSTOM")).thenReturn(false);
        when(customStore.contains(eq(scope), eq("ZZZCUSTOM"))).thenReturn(true);

        assertTrue(service.isValidWord("zzzcustom", scope));

        verify(customStore).contains(scope, "ZZZCUSTOM");
        verify(customStore, never())
                .contains(eq(WordVerificationService.GLOBAL_SCOPE), anyString());
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>The no-scope overload is a convenience wrapper that must delegate to
     * the scoped overload using {@link WordVerificationService#GLOBAL_SCOPE}.
     */
    @Test
    void isValidWord_noScopeOverload_usesGlobalScope() {
        when(trie.contains("APPLE")).thenReturn(false);
        when(customStore.contains(WordVerificationService.GLOBAL_SCOPE, "APPLE"))
                .thenReturn(true);

        assertTrue(service.isValidWord("apple"));

        verify(customStore).contains(WordVerificationService.GLOBAL_SCOPE, "APPLE");
    }
}
