package com.anteaters.boggle;

import com.anteaters.boggle.controller.WordVerificationController;
import com.anteaters.boggle.service.WordVerificationService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * MVC slice tests for {@link WordVerificationController}.
 *
 * <p><b>AI-GENERATED:</b> This test class was generated by AI, namely Opus4.7.
 *
 * <h2>What this test class covers</h2>
 * This test uses {@link WebMvcTest} so only the web layer (controller + MVC
 * configuration) is loaded. The single downstream dependency,
 * {@link WordVerificationService}, is replaced with a Mockito bean so we can
 * isolate controller behavior from dictionary state.
 *
 * <p>Coverage goals:
 * <ul>
 *   <li>{@code GET /api/verify?word=...} returns a JSON body with the exact
 *       {@code word} echoed back and a {@code valid} boolean reflecting the
 *       service result.</li>
 *   <li>The controller delegates validation to
 *       {@link WordVerificationService#isValidWord(String)} and does not
 *       attempt to normalize the word itself — normalization is the service's
 *       responsibility.</li>
 *   <li>Missing the required {@code word} parameter yields HTTP 400.</li>
 *   <li>An empty {@code word} value is forwarded as-is and still produces a
 *       200 response with whatever the service returns.</li>
 * </ul>
 */
@WebMvcTest(WordVerificationController.class)
@AutoConfigureMockMvc
public class WordVerificationControllerTest {

    /**
     * MockMvc performs HTTP-like calls against the controller without
     * starting a real server.
     */
    @Autowired
    private MockMvc mockMvc;

    /**
     * The controller's only collaborator. Replaced with a Mockito bean so we
     * can script validation outcomes per test.
     */
    @MockitoBean
    private WordVerificationService verificationService;

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>When the service says the word is valid, the response should be
     * {@code {"word":"APPLE","valid":true}} with HTTP 200.
     */
    @Test
    void verify_validWord_returnsValidTrue() throws Exception {
        when(verificationService.isValidWord(eq("APPLE"))).thenReturn(true);

        mockMvc.perform(get("/api/verify").param("word", "APPLE"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.word").value("APPLE"))
                .andExpect(jsonPath("$.valid").value(true));

        verify(verificationService).isValidWord("APPLE");
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>When the service says the word is invalid, the response should echo
     * the input and set {@code valid} to {@code false}.
     */
    @Test
    void verify_invalidWord_returnsValidFalse() throws Exception {
        when(verificationService.isValidWord(eq("ZXQV"))).thenReturn(false);

        mockMvc.perform(get("/api/verify").param("word", "ZXQV"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.word").value("ZXQV"))
                .andExpect(jsonPath("$.valid").value(false));
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>The controller itself does not normalize input — normalization is the
     * service's job. This test feeds mixed-case input and asserts that:
     * <ul>
     *   <li>The response's {@code word} field preserves the original casing.</li>
     *   <li>The service is invoked with the raw input (not pre-normalized).</li>
     * </ul>
     */
    @Test
    void verify_doesNotPreNormalizeInput_forwardsRawWord() throws Exception {
        when(verificationService.isValidWord(eq("Apple"))).thenReturn(true);

        mockMvc.perform(get("/api/verify").param("word", "Apple"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.word").value("Apple"))
                .andExpect(jsonPath("$.valid").value(true));

        verify(verificationService).isValidWord("Apple");
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>Omitting the required {@code word} query parameter should return
     * HTTP 400 Bad Request, produced by Spring's parameter binding.
     */
    @Test
    void verify_missingWordParam_returns400() throws Exception {
        mockMvc.perform(get("/api/verify"))
                .andExpect(status().isBadRequest());
    }

    /**
     * <p><b>AI-GENERATED:</b> This test method was generated by AI, namely Opus4.7.
     *
     * <p>An empty {@code word} value is still a bound parameter and should
     * reach the controller. Whatever the service decides (here, invalid) is
     * what the body should reflect.
     */
    @Test
    void verify_emptyWordParam_isForwardedToService() throws Exception {
        when(verificationService.isValidWord(eq(""))).thenReturn(false);

        mockMvc.perform(get("/api/verify").param("word", ""))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.word").value(""))
                .andExpect(jsonPath("$.valid").value(false));

        verify(verificationService).isValidWord("");
    }
}
